Repository we-are-dj/server, pull requests merged in 2021-09, with the labels that each got.

#68 Feature/socket
  build.gradle
  src/main/java/com/dj/server/api/common/controller/MainController.java
  src/main/java/com/dj/server/api/room/controller/RoomController.java
  src/main/java/com/dj/server/api/room/controller/SocketController.java
  src/main/java/com/dj/server/api/room/entity/MusicRoom.java
  src/main/java/com/dj/server/api/room/entity/MusicRoomRepository.java
  src/main/java/com/dj/server/api/room/entity/MusicRoomRole.java
  src/main/java/com/dj/server/api/room/entity/MusicRoomRoleRepository.java
  src/main/java/com/dj/server/api/room/entity/RoomRole.java
  src/main/java/com/dj/server/api/room/model/dto/request/ChatMessageDTO.java
  src/main/java/com/dj/server/api/room/model/dto/request/ChatRoomDTO.java
  src/main/java/com/dj/server/api/room/service/RedisPublisher.java
  src/main/java/com/dj/server/api/room/service/RedisSubscriber.java
  src/main/java/com/dj/server/api/room/service/RoomService.java
  src/main/java/com/dj/server/api/streaming/controller/StreamingController.java
  src/main/java/com/dj/server/api/streaming/entity/StreamingRoomRepository.java
  src/main/java/com/dj/server/api/streaming/service/StreamingService.java
  src/main/java/com/dj/server/common/aop/LoggingAop.java
  src/main/java/com/dj/server/common/config/jwt/JwtConfig.java
  src/main/java/com/dj/server/common/config/redis/RedisConfig.java
  src/main/java/com/dj/server/common/config/websocket/WebSocketConfig.java
  src/main/java/com/dj/server/common/interceptor/WebsocketInterceptor.java
  src/main/java/com/dj/server/common/jwt/JwtUtil.java
  src/main/resources/application.yml
  src/main/resources/static/app.js
  src/main/resources/static/index.html
  src/main/resources/static/temp
Labels: feature

#70 WebSocket Test Deploy
  build.gradle
  src/main/java/com/dj/server/api/common/controller/MainController.java
  src/main/java/com/dj/server/api/common/controller/MemberControllerAdvice.java
  src/main/java/com/dj/server/api/member/repository/MemberQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/musiclist/service/MusicListService.java
  src/main/java/com/dj/server/api/playlist/service/PlayListService.java
  src/main/java/com/dj/server/api/room/controller/RoomController.java
  src/main/java/com/dj/server/api/room/controller/SocketController.java
  src/main/java/com/dj/server/api/room/entity/MusicRoom.java
  src/main/java/com/dj/server/api/room/entity/MusicRoomRepository.java
  src/main/java/com/dj/server/api/room/entity/MusicRoomRole.java
  src/main/java/com/dj/server/api/room/entity/MusicRoomRoleRepository.java
  src/main/java/com/dj/server/api/room/entity/RoomRole.java
  src/main/java/com/dj/server/api/room/model/dto/request/ChatMessageDTO.java
  src/main/java/com/dj/server/api/room/model/dto/request/ChatRoomDTO.java
  src/main/java/com/dj/server/api/room/service/RedisPublisher.java
  src/main/java/com/dj/server/api/room/service/RedisSubscriber.java
  src/main/java/com/dj/server/api/room/service/RoomService.java
  src/main/java/com/dj/server/api/streaming/controller/StreamingController.java
  src/main/java/com/dj/server/api/streaming/entity/StreamingRoomRepository.java
  src/main/java/com/dj/server/api/streaming/service/StreamingService.java
  src/main/java/com/dj/server/common/aop/LoggingAop.java
  src/main/java/com/dj/server/common/config/jwt/JwtConfig.java
  src/main/java/com/dj/server/common/config/redis/RedisConfig.java
  src/main/java/com/dj/server/common/config/websocket/WebSocketConfig.java
  src/main/java/com/dj/server/common/exception/common/BizException.java
  src/main/java/com/dj/server/common/exception/common/ErrorCode.java
  src/main/java/com/dj/server/common/exception/member/MemberCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/member/MemberErrorCode.java
  src/main/java/com/dj/server/common/exception/member/MemberException.java
  src/main/java/com/dj/server/common/exception/member/MemberPermitErrorCode.java
  src/main/java/com/dj/server/common/exception/musicList/MusicListCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/musicList/MusicListErrorCode.java
  src/main/java/com/dj/server/common/exception/musicList/MusicListException.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListErrorCode.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListException.java
  src/main/java/com/dj/server/common/interceptor/JwtAuthInterceptor.java
  src/main/java/com/dj/server/common/interceptor/WebsocketInterceptor.java
  src/main/java/com/dj/server/common/jwt/JwtUtil.java
  src/main/java/com/dj/server/test/controller/ExceptionController.java
  src/main/resources/application.yml
  src/main/resources/static/app.js
  src/main/resources/static/index.html
  src/main/resources/static/temp
  src/test/java/com/dj/server/common/exception/member/BizExceptionTest.java
Labels: Deploy

#77 Hotfix/http method
  src/main/java/com/dj/server/api/common/controller/MainControllerAdvice.java
  src/main/java/com/dj/server/api/musiclist/controller/MusicListController.java
  src/main/java/com/dj/server/api/musiclist/controller/MusicListControllerAdvice.java
  src/main/java/com/dj/server/api/musiclist/dto/request/MusicListDeleteRequestDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/request/MusicListModifyRequestDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/request/MusicListSaveRequestDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/response/MusicAllListResponseDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/response/MusicListModifyResponseDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/response/MusicListSaveResponseDTO.java
  src/main/java/com/dj/server/api/musiclist/entity/MusicList.java
  src/main/java/com/dj/server/api/musiclist/repository/MusicListQueryDSLRepository.java
  src/main/java/com/dj/server/api/musiclist/repository/MusicListQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/musiclist/repository/MusicListRepository.java
  src/main/java/com/dj/server/api/musiclist/service/MusicListService.java
  src/main/java/com/dj/server/common/config/common/WebConfig.java
  src/main/java/com/dj/server/common/config/security/SecurityConfig.java
  src/main/java/com/dj/server/common/exception/common/BizException.java
  src/main/java/com/dj/server/common/exception/common/ErrorCode.java
  src/main/java/com/dj/server/common/exception/common/GeneralErrorCode.java
  src/main/java/com/dj/server/common/exception/common/ValidParameterException.java
  src/main/java/com/dj/server/common/exception/member/enums/MemberCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/member/enums/MemberPermitErrorCode.java
  src/main/java/com/dj/server/common/exception/musicList/enums/MusicListCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/musicList/handler/InvalidModifyMusicListParameterException.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListCrudErrorCode.java
  src/main/resources/application.yml
  src/test/java/com/dj/server/api/member/controller/MemberControllerTest.java
  src/test/java/com/dj/server/api/musiclist/controller/MusicListControllerTest.java
  src/test/java/com/dj/server/api/musiclist/entity/MusicListTests.java
  src/test/java/com/dj/server/api/playlist/entity/MemberPlayListEntityTest.java
  src/test/java/com/dj/server/common/dummy/musiclist/MusicListDummy.java
  src/test/java/com/dj/server/common/dummy/playlist/PlayListDummy.java
  src/test/java/com/dj/server/common/filter/CountryFilterTest.java
  src/test/resources/application.yml
Labels: hotfix

#78 Develop
  src/main/java/com/dj/server/api/common/controller/MainControllerAdvice.java
  src/main/java/com/dj/server/api/musiclist/controller/MusicListController.java
  src/main/java/com/dj/server/api/musiclist/controller/MusicListControllerAdvice.java
  src/main/java/com/dj/server/api/musiclist/dto/request/MusicListDeleteRequestDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/request/MusicListModifyRequestDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/request/MusicListSaveRequestDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/response/MusicAllListResponseDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/response/MusicListModifyResponseDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/response/MusicListSaveResponseDTO.java
  src/main/java/com/dj/server/api/musiclist/entity/MusicList.java
  src/main/java/com/dj/server/api/musiclist/repository/MusicListQueryDSLRepository.java
  src/main/java/com/dj/server/api/musiclist/repository/MusicListQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/musiclist/repository/MusicListRepository.java
  src/main/java/com/dj/server/api/musiclist/service/MusicListService.java
  src/main/java/com/dj/server/common/config/common/WebConfig.java
  src/main/java/com/dj/server/common/config/security/SecurityConfig.java
  src/main/java/com/dj/server/common/exception/common/BizException.java
  src/main/java/com/dj/server/common/exception/common/ErrorCode.java
  src/main/java/com/dj/server/common/exception/common/GeneralErrorCode.java
  src/main/java/com/dj/server/common/exception/common/ValidParameterException.java
  src/main/java/com/dj/server/common/exception/member/enums/MemberCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/member/enums/MemberPermitErrorCode.java
  src/main/java/com/dj/server/common/exception/musicList/enums/MusicListCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/musicList/handler/InvalidModifyMusicListParameterException.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListCrudErrorCode.java
  src/main/resources/application.yml
  src/test/java/com/dj/server/api/member/controller/MemberControllerTest.java
  src/test/java/com/dj/server/api/musiclist/controller/MusicListControllerTest.java
  src/test/java/com/dj/server/api/musiclist/entity/MusicListTests.java
  src/test/java/com/dj/server/api/playlist/entity/MemberPlayListEntityTest.java
  src/test/java/com/dj/server/common/dummy/musiclist/MusicListDummy.java
  src/test/java/com/dj/server/common/dummy/playlist/PlayListDummy.java
  src/test/java/com/dj/server/common/filter/CountryFilterTest.java
  src/test/resources/application.yml
Labels: Deploy, hotfix

#79 #75 hotfix: activate cors setting
  src/main/java/com/dj/server/common/config/security/SecurityConfig.java
Labels: hotfix

#80 Develop
  src/main/java/com/dj/server/common/config/security/SecurityConfig.java
Labels: hotfix

#81 Feature/modify music list
  src/test/java/com/dj/server/api/musiclist/controller/MusicListControllerTest.java
Labels: Test, refactoring, change

#84 Hotfix/locale
  src/main/java/com/dj/server/common/filter/CountryFilter.java
Labels: refactoring, change

#82 Develop
  src/main/java/com/dj/server/common/filter/CountryFilter.java
  src/test/java/com/dj/server/api/musiclist/controller/MusicListControllerTest.java
Labels: Test, Deploy, refactoring, change

#87 request server resource without jwt token
  src/main/java/com/dj/server/api/common/controller/GeneralControllerAdvice.java
  src/main/java/com/dj/server/api/common/response/ErrorResponseDTO.java
  src/main/java/com/dj/server/api/musiclist/controller/MusicListController.java
  src/main/java/com/dj/server/api/musiclist/controller/MusicListControllerAdvice.java
  src/main/java/com/dj/server/api/musiclist/dto/request/MusicListSaveRequestDTO.java
  src/main/java/com/dj/server/api/musiclist/service/MusicListService.java
  src/main/java/com/dj/server/api/playlist/controller/PlayListController.java
  src/main/java/com/dj/server/api/playlist/model/dto/request/PlayListSaveRequestDTO.java
  src/main/java/com/dj/server/api/properties/entity/Property.java
  src/main/java/com/dj/server/api/properties/model/dto/PropertyDTO.java
  src/main/java/com/dj/server/api/properties/repository/PropertyRepository.java
  src/main/java/com/dj/server/api/properties/service/PropertyService.java
  src/main/java/com/dj/server/common/config/common/WebConfig.java
  src/main/java/com/dj/server/common/exception/musicList/handler/InvalidMusicListParameterException.java
  src/main/java/com/dj/server/common/exception/property/PropertyErrorCode.java
  src/main/java/com/dj/server/common/interceptor/JwtAuthInterceptor.java
  src/test/java/com/dj/server/api/musiclist/controller/MusicControllerTest.java
  src/test/java/com/dj/server/api/playlist/controller/PlayListControllerTest.java
  src/test/java/com/dj/server/api/property/PropertyTest.java
Labels: feature, config, change

#89 검색기능 및 jwt 패스 기능 배포합니다.
  src/main/java/com/dj/server/api/common/controller/GeneralControllerAdvice.java
  src/main/java/com/dj/server/api/common/response/ErrorResponseDTO.java
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/musiclist/controller/MusicListController.java
  src/main/java/com/dj/server/api/musiclist/controller/MusicListControllerAdvice.java
  src/main/java/com/dj/server/api/musiclist/dto/request/MusicListSaveRequestDTO.java
  src/main/java/com/dj/server/api/musiclist/service/MusicListService.java
  src/main/java/com/dj/server/api/playlist/controller/PlayListController.java
  src/main/java/com/dj/server/api/playlist/entity/PlayList.java
  src/main/java/com/dj/server/api/playlist/model/dto/request/PlayListSaveRequestDTO.java
  src/main/java/com/dj/server/api/playlist/repository/PlayListQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/playlist/service/PlayListService.java
  src/main/java/com/dj/server/api/properties/entity/Property.java
  src/main/java/com/dj/server/api/properties/model/dto/PropertyDTO.java
  src/main/java/com/dj/server/api/properties/repository/PropertyRepository.java
  src/main/java/com/dj/server/api/properties/service/PropertyService.java
  src/main/java/com/dj/server/api/room/controller/RoomController.java
  src/main/java/com/dj/server/api/room/entity/AccessUser.java
  src/main/java/com/dj/server/api/room/entity/MusicRoom.java
  src/main/java/com/dj/server/api/room/entity/MusicRoomRepository.java
  src/main/java/com/dj/server/api/room/entity/MusicRoomRole.java
  src/main/java/com/dj/server/api/room/entity/RoomRole.java
  src/main/java/com/dj/server/api/room/entity/enums/RoomRole.java
  src/main/java/com/dj/server/api/room/model/dto/request/MusicRoomSaveRequestDTO.java
  src/main/java/com/dj/server/api/room/model/dto/request/MusicRoomSearchRequestDTO.java
  src/main/java/com/dj/server/api/room/model/dto/response/MusicRoomJoinResponseDTO.java
  src/main/java/com/dj/server/api/room/model/dto/response/MusicRoomSaveResponseDTO.java
  src/main/java/com/dj/server/api/room/model/dto/response/MusicRoomSearchResponseDTO.java
  src/main/java/com/dj/server/api/room/repository/AccessUserRepository.java
  src/main/java/com/dj/server/api/room/repository/MusicRoomRoleRepository.java
  src/main/java/com/dj/server/api/room/repository/room/MusicRoomQueryDSLRepository.java
  src/main/java/com/dj/server/api/room/repository/room/MusicRoomQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/room/repository/room/MusicRoomRepository.java
  src/main/java/com/dj/server/api/room/service/MusicRoomService.java
  src/main/java/com/dj/server/common/config/common/WebConfig.java
  src/main/java/com/dj/server/common/exception/musicList/handler/InvalidMusicListParameterException.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/property/PropertyErrorCode.java
  src/main/java/com/dj/server/common/exception/room/RoomCrudErrorCode.java
  src/main/java/com/dj/server/common/interceptor/JwtAuthInterceptor.java
  src/main/java/com/dj/server/common/interceptor/WebsocketInterceptor.java
  src/main/resources/application.yml
  src/test/java/com/dj/server/api/musiclist/controller/MusicControllerTest.java
  src/test/java/com/dj/server/api/playlist/controller/PlayListControllerTest.java
  src/test/java/com/dj/server/api/property/PropertyTest.java
Labels: Deploy

#96 #92 Fix Logging System
  src/main/java/com/dj/server/api/common/request/LoggingSupport.java
  src/main/java/com/dj/server/common/aop/LoggingAop.java
Labels: bug

#97 Feature/refactoring
  src/main/java/com/dj/server/api/member/repository/MemberRepository.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/room/service/MusicRoomService.java
  src/test/java/com/dj/server/api/member/service/MemberServiceTests.java
  src/test/java/com/dj/server/api/playlist/service/PlayListServiceTest.java
Labels: refactoring

#98 Deploy
  src/main/java/com/dj/server/api/common/request/LoggingSupport.java
  src/main/java/com/dj/server/api/member/repository/MemberRepository.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/room/service/MusicRoomService.java
  src/main/java/com/dj/server/common/aop/LoggingAop.java
  src/test/java/com/dj/server/api/member/service/MemberServiceTests.java
  src/test/java/com/dj/server/api/playlist/service/PlayListServiceTest.java
Labels: bug, refactoring
