Repository we-are-dj/server, pull requests merged in 2021-08, with the labels that each got.

#9 #7 Added Entity Class & Repository
  .settings/org.eclipse.buildship.core.prefs
  .settings/org.eclipse.jdt.core.prefs
  bin/main/application.yml
  bin/main/static/temp
  bin/main/templates/temp
  bin/test/application.yml
  build.gradle
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/entity/MemberRepository.java
  src/main/java/com/dj/server/api/member/entity/MemberRole.java
  src/main/java/com/dj/server/api/member/entity/musiclist/MusicList.java
  src/main/java/com/dj/server/api/member/entity/musiclist/MusicListRepository.java
  src/main/java/com/dj/server/api/member/entity/playlist/MemberPlayList.java
  src/main/java/com/dj/server/api/member/entity/playlist/MemberPlayListRepository.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/streaming/controller/StreamingController.java
  src/main/java/com/dj/server/api/streaming/entity/StreamingRoom.java
  src/main/java/com/dj/server/api/streaming/entity/StreamingRoomRepository.java
  src/main/java/com/dj/server/api/streaming/service/StreamingService.java
  src/main/java/com/dj/server/status/StatusController.java
  src/main/resources/application.yml
  src/test/java/com/dj/server/api/member/entity/MemberEntityTests.java
  src/test/resources/application.yml
Labels: config

#11 Feature/cors
  build.gradle
  src/main/java/com/dj/server/api/common/controller/TestController.java
  src/main/java/com/dj/server/api/member/entity/MemberRole.java
  src/main/java/com/dj/server/config/security/SecurityConfig.java
  src/main/java/com/dj/server/exception/member/MemberDuplicateException.java
  src/main/java/com/dj/server/exception/member/MemberErrorCode.java
  src/main/java/com/dj/server/exception/member/MemberException.java
  src/main/java/com/dj/server/exception/playlist/PlayListErrorCode.java
  src/main/java/com/dj/server/exception/playlist/PlayListException.java
  src/main/resources/application.yml
  src/test/java/com/dj/server/config/security/SecurityConfigTest.java
  src/test/java/com/dj/server/exception/member/MemberExceptionTest.java
Labels: config

#12 #10 Added Entity Test
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/entity/musiclist/MusicList.java
  src/main/java/com/dj/server/api/member/entity/playlist/MemberPlayList.java
  src/test/java/com/dj/server/api/member/entity/MemberEntityTests.java
  src/test/java/com/dj/server/api/member/entity/musiclist/MusicListTests.java
  src/test/java/com/dj/server/api/member/entity/playlist/MemberPlayListEntityTests.java
  src/test/java/com/dj/server/common/dummy/member/MemberDummy.java
  src/test/java/com/dj/server/common/dummy/playlist/MemberPlayListDummy.java
  src/test/resources/application.yml
Labels: Test

#14 Real Server Deploy
  .github/workflows/deploy.yml
  .settings/org.eclipse.buildship.core.prefs
  .settings/org.eclipse.jdt.core.prefs
  bin/main/application.yml
  bin/main/static/temp
  bin/main/templates/temp
  bin/test/application.yml
  build.gradle
  src/main/java/com/dj/server/api/common/controller/TestController.java
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/entity/MemberRepository.java
  src/main/java/com/dj/server/api/member/entity/MemberRole.java
  src/main/java/com/dj/server/api/member/entity/musiclist/MusicList.java
  src/main/java/com/dj/server/api/member/entity/musiclist/MusicListRepository.java
  src/main/java/com/dj/server/api/member/entity/playlist/MemberPlayList.java
  src/main/java/com/dj/server/api/member/entity/playlist/MemberPlayListRepository.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/streaming/controller/StreamingController.java
  src/main/java/com/dj/server/api/streaming/entity/StreamingRoom.java
  src/main/java/com/dj/server/api/streaming/entity/StreamingRoomRepository.java
  src/main/java/com/dj/server/api/streaming/service/StreamingService.java
  src/main/java/com/dj/server/config/security/SecurityConfig.java
  src/main/java/com/dj/server/exception/member/MemberDuplicateException.java
  src/main/java/com/dj/server/exception/member/MemberErrorCode.java
  src/main/java/com/dj/server/exception/member/MemberException.java
  src/main/java/com/dj/server/exception/playlist/PlayListErrorCode.java
  src/main/java/com/dj/server/exception/playlist/PlayListException.java
  src/main/java/com/dj/server/status/StatusController.java
  src/main/resources/application.yml
  src/test/java/com/dj/server/api/member/entity/MemberEntityTests.java
  src/test/java/com/dj/server/api/member/entity/musiclist/MusicListTests.java
  src/test/java/com/dj/server/api/member/entity/playlist/MemberPlayListEntityTests.java
  src/test/java/com/dj/server/common/dummy/member/MemberDummy.java
  src/test/java/com/dj/server/common/dummy/playlist/MemberPlayListDummy.java
  src/test/java/com/dj/server/config/security/SecurityConfigTest.java
  src/test/java/com/dj/server/exception/member/MemberExceptionTest.java
  src/test/resources/application.yml
Labels: Deploy

#17 #16 Added Create Common ResponseDTO
  build.gradle
  src/main/java/com/dj/server/api/common/controller/TestController.java
  src/main/java/com/dj/server/api/common/response/ResponseDTO.java
  src/main/java/com/dj/server/api/member/dto/MemberResponseDTO.java
  src/main/resources/application.yml
  src/test/java/com/dj/server/api/common/response/ResponseDTOTests.java
Labels: feature

#23 Feature/querydsl setting
  .gitignore
  .settings/org.eclipse.buildship.core.prefs
  .settings/org.eclipse.jdt.core.prefs
  bin/main/application.yml
  bin/main/static/temp
  bin/main/templates/temp
  bin/test/application.yml
  build.gradle
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/entity/MemberQueryDSLRepository.java
  src/main/java/com/dj/server/api/member/entity/MemberQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/member/entity/MemberRepository.java
  src/test/java/com/dj/server/api/member/entity/MemberEntityTests.java
  src/test/java/com/dj/server/api/member/entity/MemberQueryDSLTests.java
Labels: config

#24 Feature/comment
  src/main/java/com/dj/server/api/common/controller/TestController.java
  src/main/java/com/dj/server/api/common/response/ResponseDTO.java
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/entity/MemberRepository.java
  src/main/java/com/dj/server/api/member/entity/musiclist/MusicList.java
  src/main/java/com/dj/server/api/member/entity/musiclist/MusicListRepository.java
  src/main/java/com/dj/server/api/member/entity/playlist/MemberPlayList.java
  src/main/java/com/dj/server/api/member/entity/playlist/MemberPlayListRepository.java
  src/main/java/com/dj/server/api/streaming/entity/StreamingRoom.java
  src/main/java/com/dj/server/config/security/SecurityConfig.java
  src/main/java/com/dj/server/config/swagger/SwaggerConfig.java
  src/main/java/com/dj/server/exception/member/MemberException.java
  src/main/java/com/dj/server/exception/member/MemberPermitErrorCode.java
  src/main/java/com/dj/server/exception/playlist/PlayListErrorCode.java
  src/main/java/com/dj/server/exception/playlist/PlayListException.java
  src/main/java/com/dj/server/status/StatusController.java
  src/test/java/com/dj/server/common/dummy/member/MemberDummy.java
  src/test/java/com/dj/server/common/dummy/playlist/MemberPlayListDummy.java
Labels: documentation

#25 #18 Added Aop Setting
  build.gradle
  src/main/java/com/dj/server/WeAreDjApplication.java
  src/main/java/com/dj/server/aop/LoggingAop.java
  src/main/java/com/dj/server/api/common/controller/TestController.java
  src/main/java/com/dj/server/api/common/response/ResponseDTO.java
  src/main/java/com/dj/server/api/member/dto/request/MemberTestRequestDTO.java
  src/main/java/com/dj/server/api/member/dto/response/MemberResponseDTO.java
Labels: config

#31 Fix Entity Field Name
  src/main/java/com/dj/server/api/member/dto/request/KakaoProfile.java
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/test/java/com/dj/server/api/member/entity/MemberEntityTests.java
Labels: bug, Deploy

#33 Feature/aop refactoring
  build.gradle
  src/main/java/com/dj/server/api/common/request/LoggingSupport.java
  src/main/java/com/dj/server/api/common/response/ResponseDTO.java
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/service/MemberArgumentResolver.java
  src/main/java/com/dj/server/api/member/service/OAuth2Provider.java
  src/main/java/com/dj/server/common/aop/LoggingAop.java
  src/main/java/com/dj/server/common/config/jwt/JwtConfig.java
  src/main/java/com/dj/server/test/controller/AopController.java
  src/main/java/com/dj/server/test/controller/KakaoOauth2Controller.java
  src/main/java/com/dj/server/test/controller/ResponseController.java
  src/test/java/com/dj/server/api/common/response/ResponseDTOTests.java
Labels: refactoring

#36 Feature/refactoring
  src/main/java/com/dj/server/api/common/response/ResponseDTO.java
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/dto/request/KakaoAccount.java
  src/main/java/com/dj/server/api/member/dto/request/KakaoProfile.java
  src/main/java/com/dj/server/api/member/dto/request/KakaoRequest.java
  src/main/java/com/dj/server/api/member/dto/request/KakaoToken.java
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/entity/SocialType.java
  src/main/java/com/dj/server/api/member/model/MemberRole.java
  src/main/java/com/dj/server/api/member/model/SocialType.java
  src/main/java/com/dj/server/api/member/repository/MemberQueryDSLRepository.java
  src/main/java/com/dj/server/api/member/repository/MemberQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/member/repository/MemberRepository.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/member/service/jwt/JwtUtil.java
  src/main/java/com/dj/server/api/musiclist/MusicList.java
  src/main/java/com/dj/server/api/musiclist/MusicListRepository.java
  src/main/java/com/dj/server/api/playlist/MemberPlayList.java
  src/main/java/com/dj/server/api/playlist/MemberPlayListRepository.java
  src/main/java/com/dj/server/common/config/jwt/JwtConfig.java
  src/main/java/com/dj/server/common/config/security/SecurityConfig.java
  src/main/java/com/dj/server/common/exception/member/MemberCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/member/MemberErrorCode.java
  src/main/java/com/dj/server/common/exception/member/MemberPermitErrorCode.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListErrorCode.java
  src/main/java/com/dj/server/common/interceptor/JwtAuthInterceptor.java
  src/main/java/com/dj/server/common/jwt/JwtUtil.java
  src/main/java/com/dj/server/test/controller/CorsController.java
  src/main/java/com/dj/server/test/controller/ResponseController.java
  src/main/java/com/dj/server/test/dto/MemberTestRequestDTO.java
  src/test/java/com/dj/server/api/member/entity/MemberEntityTests.java
  src/test/java/com/dj/server/api/member/entity/MemberQueryDSLTests.java
  src/test/java/com/dj/server/api/musiclist/MusicListTests.java
  src/test/java/com/dj/server/api/playlist/MemberPlayListEntityTests.java
  src/test/java/com/dj/server/common/dummy/member/MemberDummy.java
  src/test/java/com/dj/server/common/dummy/playlist/MemberPlayListDummy.java
  src/test/java/com/dj/server/common/exception/member/MemberExceptionTest.java
Labels: refactoring

#37 #34 Create Document
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#38 Real Server Deploy
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/com/dj/server/api/common/request/LoggingSupport.java
  src/main/java/com/dj/server/api/common/response/ResponseDTO.java
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/dto/request/KakaoAccount.java
  src/main/java/com/dj/server/api/member/dto/request/KakaoProfile.java
  src/main/java/com/dj/server/api/member/dto/request/KakaoRequest.java
  src/main/java/com/dj/server/api/member/dto/request/KakaoToken.java
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/entity/SocialType.java
  src/main/java/com/dj/server/api/member/model/MemberRole.java
  src/main/java/com/dj/server/api/member/model/SocialType.java
  src/main/java/com/dj/server/api/member/repository/MemberQueryDSLRepository.java
  src/main/java/com/dj/server/api/member/repository/MemberQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/member/repository/MemberRepository.java
  src/main/java/com/dj/server/api/member/service/MemberArgumentResolver.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/member/service/OAuth2Provider.java
  src/main/java/com/dj/server/api/member/service/jwt/JwtUtil.java
  src/main/java/com/dj/server/api/musiclist/MusicList.java
  src/main/java/com/dj/server/api/musiclist/MusicListRepository.java
  src/main/java/com/dj/server/api/playlist/MemberPlayList.java
  src/main/java/com/dj/server/api/playlist/MemberPlayListRepository.java
  src/main/java/com/dj/server/common/aop/LoggingAop.java
  src/main/java/com/dj/server/common/config/jwt/JwtConfig.java
  src/main/java/com/dj/server/common/config/security/SecurityConfig.java
  src/main/java/com/dj/server/common/exception/member/MemberCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/member/MemberErrorCode.java
  src/main/java/com/dj/server/common/exception/member/MemberPermitErrorCode.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListErrorCode.java
  src/main/java/com/dj/server/common/interceptor/JwtAuthInterceptor.java
  src/main/java/com/dj/server/common/jwt/JwtUtil.java
  src/main/java/com/dj/server/test/controller/AopController.java
  src/main/java/com/dj/server/test/controller/CorsController.java
  src/main/java/com/dj/server/test/controller/KakaoOauth2Controller.java
  src/main/java/com/dj/server/test/controller/ResponseController.java
  src/main/java/com/dj/server/test/dto/MemberTestRequestDTO.java
  src/test/java/com/dj/server/api/common/response/ResponseDTOTests.java
  src/test/java/com/dj/server/api/member/entity/MemberEntityTests.java
  src/test/java/com/dj/server/api/member/entity/MemberQueryDSLTests.java
  src/test/java/com/dj/server/api/musiclist/MusicListTests.java
  src/test/java/com/dj/server/api/playlist/MemberPlayListEntityTests.java
  src/test/java/com/dj/server/common/dummy/member/MemberDummy.java
  src/test/java/com/dj/server/common/dummy/playlist/MemberPlayListDummy.java
  src/test/java/com/dj/server/common/exception/member/MemberExceptionTest.java
Labels: Deploy

#42 #41 Added Record User IP
  scripts/deploy.sh
  src/main/java/com/dj/server/api/common/request/LoggingSupport.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/common/aop/LoggingAop.java
Labels: feature, warning

#43 Real Server Deploy
  scripts/deploy.sh
  src/main/java/com/dj/server/api/common/request/LoggingSupport.java
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/dto/request/KakaoAccount.java
  src/main/java/com/dj/server/api/member/dto/request/KakaoProfile.java
  src/main/java/com/dj/server/api/member/dto/request/KakaoRequest.java
  src/main/java/com/dj/server/api/member/dto/request/KakaoToken.java
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/repository/MemberRepository.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/common/aop/LoggingAop.java
  src/main/java/com/dj/server/common/config/security/SecurityConfig.java
Labels: Deploy, warning

#47 #45 move kakao oauth2 class package, rename enum packages, code make …
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  scripts/deploy.sh
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/dto/request/MemberReqeustDTO.java
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/entity/enums/MemberRole.java
  src/main/java/com/dj/server/api/member/entity/enums/SocialType.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/member/service/oauth2/kakao/request/KakaoRequest.java
  src/main/java/com/dj/server/api/member/service/oauth2/kakao/vo/KakaoAccount.java
  src/main/java/com/dj/server/api/member/service/oauth2/kakao/vo/KakaoProfile.java
  src/main/java/com/dj/server/api/member/service/oauth2/kakao/vo/KakaoToken.java
  src/main/java/com/dj/server/common/jwt/JwtUtil.java
  src/test/java/com/dj/server/api/common/response/ResponseDTOTests.java
  src/test/java/com/dj/server/common/dummy/member/MemberDummy.java
  src/test/java/com/dj/server/common/exception/member/MemberExceptionTest.java
Labels: refactoring

#51 Feature/java version up
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/dj/server/api/common/controller/MainController.java
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/musiclist/MusicList.java
  src/main/java/com/dj/server/api/playlist/MemberPlayList.java
  src/main/java/com/dj/server/api/streaming/entity/StreamingRoom.java
  src/test/java/com/dj/server/common/version/JavaVersionTest.java
Labels: version-up

#52 Java Version Up Server Deploy
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/dj/server/api/common/controller/MainController.java
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/dto/request/MemberReqeustDTO.java
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/entity/enums/MemberRole.java
  src/main/java/com/dj/server/api/member/entity/enums/SocialType.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/member/service/oauth2/kakao/request/KakaoRequest.java
  src/main/java/com/dj/server/api/member/service/oauth2/kakao/vo/KakaoAccount.java
  src/main/java/com/dj/server/api/member/service/oauth2/kakao/vo/KakaoProfile.java
  src/main/java/com/dj/server/api/member/service/oauth2/kakao/vo/KakaoToken.java
  src/main/java/com/dj/server/api/musiclist/MusicList.java
  src/main/java/com/dj/server/api/playlist/MemberPlayList.java
  src/main/java/com/dj/server/api/streaming/entity/StreamingRoom.java
  src/main/java/com/dj/server/common/jwt/JwtUtil.java
  src/test/java/com/dj/server/api/common/response/ResponseDTOTests.java
  src/test/java/com/dj/server/common/dummy/member/MemberDummy.java
  src/test/java/com/dj/server/common/exception/member/MemberExceptionTest.java
  src/test/java/com/dj/server/common/version/JavaVersionTest.java
Labels: Deploy, version-up

#53 #13 Fix MemberSts Change StatusType
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/entity/enums/SocialType.java
  src/main/java/com/dj/server/api/member/entity/enums/StatusType.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/member/service/oauth2/kakao/vo/KakaoProfile.java
  src/main/resources/application.yml
  src/test/java/com/dj/server/api/member/entity/MemberEntityTests.java
  src/test/java/com/dj/server/common/dummy/member/MemberDummy.java
  src/test/java/com/dj/server/common/exception/member/MemberExceptionTest.java
  src/test/resources/application.yml
Labels: refactoring

#54 Feature/jwt
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/dto/request/MemberReqeustDTO.java
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/model/dto/request/MemberSaveRequestDTO.java
  src/main/java/com/dj/server/api/member/model/dto/response/ResponseTokenDTO.java
  src/main/java/com/dj/server/api/member/model/vo/kakao/KakaoAccount.java
  src/main/java/com/dj/server/api/member/model/vo/kakao/KakaoProfile.java
  src/main/java/com/dj/server/api/member/model/vo/kakao/KakaoToken.java
  src/main/java/com/dj/server/api/member/repository/MemberQueryDSLRepository.java
  src/main/java/com/dj/server/api/member/repository/MemberQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/member/repository/MemberRepository.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/member/service/oauth2/kakao/request/KakaoRequest.java
  src/main/java/com/dj/server/common/config/jwt/JwtConfig.java
  src/main/java/com/dj/server/common/config/security/SecurityConfig.java
  src/main/java/com/dj/server/common/exception/member/MemberPermitErrorCode.java
  src/main/java/com/dj/server/common/interceptor/JwtAuthInterceptor.java
  src/main/java/com/dj/server/common/jwt/JwtUtil.java
  src/main/java/com/dj/server/test/controller/AopController.java
  src/main/java/com/dj/server/test/controller/CorsController.java
  src/main/java/com/dj/server/test/controller/ExceptionController.java
  src/main/java/com/dj/server/test/controller/ResponseController.java
  src/main/java/com/dj/server/test/dto/MemberResponseDTO.java
  src/test/java/com/dj/server/api/common/response/ResponseDTOTests.java
  src/test/java/com/dj/server/api/member/entity/MemberQueryDSLTests.java
  src/test/java/com/dj/server/common/config/security/SecurityConfigTest.java
  src/test/java/com/dj/server/common/interceptor/JwtAuthInterceptorTest.java
Labels: feature

#55 2021-08-15 21:09:16 Real Server Deploy
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/dto/request/MemberReqeustDTO.java
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/entity/enums/SocialType.java
  src/main/java/com/dj/server/api/member/entity/enums/StatusType.java
  src/main/java/com/dj/server/api/member/model/dto/request/MemberSaveRequestDTO.java
  src/main/java/com/dj/server/api/member/model/dto/response/ResponseTokenDTO.java
  src/main/java/com/dj/server/api/member/model/vo/kakao/KakaoAccount.java
  src/main/java/com/dj/server/api/member/model/vo/kakao/KakaoProfile.java
  src/main/java/com/dj/server/api/member/model/vo/kakao/KakaoToken.java
  src/main/java/com/dj/server/api/member/repository/MemberQueryDSLRepository.java
  src/main/java/com/dj/server/api/member/repository/MemberQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/member/repository/MemberRepository.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/member/service/oauth2/kakao/request/KakaoRequest.java
  src/main/java/com/dj/server/common/config/jwt/JwtConfig.java
  src/main/java/com/dj/server/common/config/security/SecurityConfig.java
  src/main/java/com/dj/server/common/exception/member/MemberPermitErrorCode.java
  src/main/java/com/dj/server/common/interceptor/JwtAuthInterceptor.java
  src/main/java/com/dj/server/common/jwt/JwtUtil.java
  src/main/java/com/dj/server/test/controller/AopController.java
  src/main/java/com/dj/server/test/controller/CorsController.java
  src/main/java/com/dj/server/test/controller/ExceptionController.java
  src/main/java/com/dj/server/test/controller/ResponseController.java
  src/main/java/com/dj/server/test/dto/MemberResponseDTO.java
  src/main/resources/application.yml
  src/test/java/com/dj/server/api/common/response/ResponseDTOTests.java
  src/test/java/com/dj/server/api/member/entity/MemberEntityTests.java
  src/test/java/com/dj/server/api/member/entity/MemberQueryDSLTests.java
  src/test/java/com/dj/server/common/config/security/SecurityConfigTest.java
  src/test/java/com/dj/server/common/dummy/member/MemberDummy.java
  src/test/java/com/dj/server/common/exception/member/MemberExceptionTest.java
  src/test/java/com/dj/server/common/interceptor/JwtAuthInterceptorTest.java
  src/test/resources/application.yml
Labels: Deploy

#56 Feature/playlist
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/model/dto/request/MemberSaveRequestDTO.java
  src/main/java/com/dj/server/api/member/model/dto/response/ResponseTokenDTO.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/musiclist/MusicList.java
  src/main/java/com/dj/server/api/playlist/MemberPlayListRepository.java
  src/main/java/com/dj/server/api/playlist/controller/PlayListController.java
  src/main/java/com/dj/server/api/playlist/entity/PlayList.java
  src/main/java/com/dj/server/api/playlist/model/dto/request/PlayListFetchAllRequestDTO.java
  src/main/java/com/dj/server/api/playlist/model/dto/response/MemberPlayListResponseDTO.java
  src/main/java/com/dj/server/api/playlist/repository/PlayListRepository.java
  src/main/java/com/dj/server/api/playlist/service/PlayListService.java
  src/main/java/com/dj/server/common/config/jwt/JwtConfig.java
  src/main/java/com/dj/server/test/dto/MemberResponseDTO.java
  src/test/java/com/dj/server/api/musiclist/MusicListTests.java
  src/test/java/com/dj/server/api/playlist/MemberPlayListEntityTests.java
  src/test/java/com/dj/server/common/dummy/playlist/MemberPlayListDummy.java
Labels: bug, Deploy

#58 Feature/playlist
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/model/dto/request/MemberSaveRequestDTO.java
  src/main/java/com/dj/server/api/member/model/dto/response/ResponseTokenDTO.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/musiclist/MusicList.java
  src/main/java/com/dj/server/api/playlist/MemberPlayListRepository.java
  src/main/java/com/dj/server/api/playlist/controller/PlayListController.java
  src/main/java/com/dj/server/api/playlist/entity/PlayList.java
  src/main/java/com/dj/server/api/playlist/model/dto/request/PlayListDeleteRequestDTO.java
  src/main/java/com/dj/server/api/playlist/model/dto/request/PlayListModifyRequestDTO.java
  src/main/java/com/dj/server/api/playlist/model/dto/request/PlayListSaveRequestDTO.java
  src/main/java/com/dj/server/api/playlist/model/dto/response/PlayAllListResponseDTO.java
  src/main/java/com/dj/server/api/playlist/model/dto/response/PlayListModifyResponseDTO.java
  src/main/java/com/dj/server/api/playlist/model/dto/response/PlayListSaveResponseDTO.java
  src/main/java/com/dj/server/api/playlist/repository/PlayListQueryDSLRepository.java
  src/main/java/com/dj/server/api/playlist/repository/PlayListQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/playlist/repository/PlayListRepository.java
  src/main/java/com/dj/server/api/playlist/service/PlayListService.java
  src/main/java/com/dj/server/common/config/jwt/JwtConfig.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListErrorCode.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListException.java
  src/main/java/com/dj/server/common/jwt/JwtUtil.java
  src/main/java/com/dj/server/test/dto/MemberResponseDTO.java
  src/test/java/com/dj/server/api/common/response/ResponseDTOTests.java
  src/test/java/com/dj/server/api/musiclist/MusicListTests.java
  src/test/java/com/dj/server/api/playlist/controller/PlayListControllerTest.java
  src/test/java/com/dj/server/api/playlist/entity/MemberPlayListEntityTest.java
  src/test/java/com/dj/server/api/playlist/service/PlayListServiceTest.java
  src/test/java/com/dj/server/common/dummy/member/MemberDummy.java
  src/test/java/com/dj/server/common/dummy/playlist/PlayListDummy.java
Labels: feature

#61 Feature/modify nick name
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/model/vo/kakao/KakaoProfile.java
  src/main/java/com/dj/server/api/member/repository/MemberRepository.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/musiclist/controller/MusicListController.java
  src/main/java/com/dj/server/common/exception/member/MemberCrudErrorCode.java
Labels: feature, change

#59 #50 add musicList api
  src/main/java/com/dj/server/api/musiclist/controller/MusicListController.java
  src/main/java/com/dj/server/api/musiclist/dto/request/MusicListDeleteRequestDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/request/MusicListModifyRequestDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/request/MusicListSaveRequestDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/response/MusicListSaveResponseDTO.java
  src/main/java/com/dj/server/api/musiclist/entity/MusicList.java
  src/main/java/com/dj/server/api/musiclist/repository/MusicListQueryDSLRepository.java
  src/main/java/com/dj/server/api/musiclist/repository/MusicListQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/musiclist/repository/MusicListRepository.java
  src/main/java/com/dj/server/api/musiclist/service/MusicListService.java
  src/main/java/com/dj/server/test/controller/ResponseController.java
  src/test/java/com/dj/server/api/musiclist/controller/MusicControllerTest.java
  src/test/java/com/dj/server/api/musiclist/entity/MusicListTests.java
  src/test/java/com/dj/server/api/musiclist/service/MusicServiceTest.java
  src/test/java/com/dj/server/api/playlist/controller/PlayListControllerTest.java
  src/test/java/com/dj/server/api/playlist/service/PlayListServiceTest.java
Labels: feature

#63 Real server Deploy
  src/main/java/com/dj/server/api/member/controller/MemberController.java
  src/main/java/com/dj/server/api/member/entity/Member.java
  src/main/java/com/dj/server/api/member/model/vo/kakao/KakaoProfile.java
  src/main/java/com/dj/server/api/member/repository/MemberQueryDSLRepository.java
  src/main/java/com/dj/server/api/member/repository/MemberQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/member/repository/MemberRepository.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/musiclist/MusicList.java
  src/main/java/com/dj/server/api/musiclist/MusicListRepository.java
  src/main/java/com/dj/server/api/musiclist/controller/MusicListController.java
  src/main/java/com/dj/server/api/musiclist/dto/request/MusicListDeleteRequestDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/request/MusicListModifyRequestDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/request/MusicListSaveRequestDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/response/MusicAllListResponseDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/response/MusicListModifyResponseDTO.java
  src/main/java/com/dj/server/api/musiclist/dto/response/MusicListSaveResponseDTO.java
  src/main/java/com/dj/server/api/musiclist/entity/MusicList.java
  src/main/java/com/dj/server/api/musiclist/repository/MusicListQueryDSLRepository.java
  src/main/java/com/dj/server/api/musiclist/repository/MusicListQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/musiclist/repository/MusicListRepository.java
  src/main/java/com/dj/server/api/musiclist/service/MusicListService.java
  src/main/java/com/dj/server/api/playlist/controller/PlayListController.java
  src/main/java/com/dj/server/api/playlist/entity/PlayList.java
  src/main/java/com/dj/server/api/playlist/model/dto/request/PlayListDeleteRequestDTO.java
  src/main/java/com/dj/server/api/playlist/model/dto/request/PlayListFetchAllRequestDTO.java
  src/main/java/com/dj/server/api/playlist/model/dto/request/PlayListModifyRequestDTO.java
  src/main/java/com/dj/server/api/playlist/model/dto/request/PlayListSaveRequestDTO.java
  src/main/java/com/dj/server/api/playlist/model/dto/response/PlayAllListResponseDTO.java
  src/main/java/com/dj/server/api/playlist/model/dto/response/PlayListModifyResponseDTO.java
  src/main/java/com/dj/server/api/playlist/model/dto/response/PlayListSaveResponseDTO.java
  src/main/java/com/dj/server/api/playlist/repository/PlayListQueryDSLRepository.java
  src/main/java/com/dj/server/api/playlist/repository/PlayListQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/playlist/repository/PlayListRepository.java
  src/main/java/com/dj/server/api/playlist/service/PlayListService.java
  src/main/java/com/dj/server/common/exception/member/MemberCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/member/MemberPermitErrorCode.java
  src/main/java/com/dj/server/common/exception/musicList/MusicListCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/musicList/MusicListErrorCode.java
  src/main/java/com/dj/server/common/exception/musicList/MusicListException.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListErrorCode.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListException.java
  src/main/java/com/dj/server/common/interceptor/JwtAuthInterceptor.java
  src/main/java/com/dj/server/common/jwt/JwtUtil.java
  src/main/java/com/dj/server/test/controller/ResponseController.java
  src/test/java/com/dj/server/api/common/response/ResponseDTOTests.java
  src/test/java/com/dj/server/api/musiclist/controller/MusicControllerTest.java
  src/test/java/com/dj/server/api/musiclist/entity/MusicListTests.java
  src/test/java/com/dj/server/api/musiclist/service/MusicServiceTest.java
  src/test/java/com/dj/server/api/playlist/controller/PlayListControllerTest.java
  src/test/java/com/dj/server/api/playlist/entity/MemberPlayListEntityTest.java
  src/test/java/com/dj/server/api/playlist/service/PlayListServiceTest.java
  src/test/java/com/dj/server/common/dummy/member/MemberDummy.java
  src/test/java/com/dj/server/common/dummy/playlist/PlayListDummy.java
Labels: Deploy

#67 Feature/exception refactoring
  src/main/java/com/dj/server/api/common/controller/MemberControllerAdvice.java
  src/main/java/com/dj/server/api/member/repository/MemberQueryDSLRepositoryImpl.java
  src/main/java/com/dj/server/api/member/service/MemberService.java
  src/main/java/com/dj/server/api/musiclist/service/MusicListService.java
  src/main/java/com/dj/server/api/playlist/service/PlayListService.java
  src/main/java/com/dj/server/common/exception/common/BizException.java
  src/main/java/com/dj/server/common/exception/common/ErrorCode.java
  src/main/java/com/dj/server/common/exception/member/MemberCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/member/MemberErrorCode.java
  src/main/java/com/dj/server/common/exception/member/MemberException.java
  src/main/java/com/dj/server/common/exception/member/MemberPermitErrorCode.java
  src/main/java/com/dj/server/common/exception/musicList/MusicListCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/musicList/MusicListErrorCode.java
  src/main/java/com/dj/server/common/exception/musicList/MusicListException.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListCrudErrorCode.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListErrorCode.java
  src/main/java/com/dj/server/common/exception/playlist/PlayListException.java
  src/main/java/com/dj/server/common/interceptor/JwtAuthInterceptor.java
  src/main/java/com/dj/server/common/jwt/JwtUtil.java
  src/main/java/com/dj/server/test/controller/ExceptionController.java
  src/test/java/com/dj/server/common/exception/member/BizExceptionTest.java
Labels: refactoring
